/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlynhankhau.ui;

import com.mycompany.quanlynhankhau.Helpers.DataValidator;
import com.mycompany.quanlynhankhau.Helpers.MessageDialogHelper;
import com.mycompany.quanlynhankhau.Thongtin.CachLy;
import com.mycompany.quanlynhankhau.dao.CachLyDao;
import static com.sun.corba.se.impl.util.Utility.printStackTrace;

/**
 *
 * @author HP
 */
public class CL_Info extends javax.swing.JPanel {
    private String currentPC_IDNK;
    /**
     * Creates new form CL_Info
     */
    public CL_Info() {
        initComponents();
    }

    public CL_Info(CachLy cl) {
        initComponents();
        
        info_IDNK_PC_text.setText(cl.getIdNK());
        info_name_PC_text.setText(cl.getHoTen());
        info_CCCD_PC_text.setText(cl.getCccd());              
        info_methodTest_PC_text.setText(cl.getHinhThuc());        
        info_timeTest_PC_text.setText(cl.getTgKiemTra());
        info_startTimeCL_PC_text.setText(cl.getTgBatDau());
        if (cl.getKiemTra().equals("Đã thực hiện")){
            info_done_test.setSelected(true);
        }
        else{
            info_notdone_test.setSelected(true);
        }
        
        if (cl.getKetQua().equals("Dương tính")){
            info_positive.setSelected(true);
        }
        else{
            info_negative.setSelected(true);
        }
        
        switch (cl.getMucDo()) {
            case "1(F2)":
                info_level_F2.setSelected(true);
                break;
            case "2(F1)":
                info_level_F1.setSelected(true);
                break;
            default:
                info_level_F0.setSelected(true);
                break;
        }
        
        if (cl.getTrangThai().equals("Tại nhà")){
            info_Cachly_TN.setSelected(true);
        }
        else{
            info_Cachly_KVCL.setSelected(true);
        }
        
        currentPC_IDNK = info_IDNK_PC_text.getText();
    }
    
    public void SetEditableTextField(boolean isEditable){
        info_IDNK_PC_text.setEditable(isEditable);    
        info_name_PC_text.setEditable(isEditable);
        info_CCCD_PC_text.setEditable(isEditable);        
        info_timeTest_PC_text.setEditable(isEditable);       
        info_methodTest_PC_text.setEditable(isEditable);      
        info_startTimeCL_PC_text.setEditable(isEditable); 
        
        update_PC_Btn.setVisible(isEditable);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        info_IDNK_PC_text = new javax.swing.JTextField();
        info_name_PC_text = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        info_methodTest_PC_text = new javax.swing.JTextField();
        info_timeTest_PC_text = new javax.swing.JTextField();
        update_PC_Btn = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        info_done_test = new javax.swing.JRadioButton();
        info_notdone_test = new javax.swing.JRadioButton();
        info_CCCD_PC_text = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        info_startTimeCL_PC_text = new javax.swing.JTextField();
        info_positive = new javax.swing.JRadioButton();
        info_negative = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        info_level_F2 = new javax.swing.JRadioButton();
        info_level_F1 = new javax.swing.JRadioButton();
        info_level_F0 = new javax.swing.JRadioButton();
        info_Cachly_TN = new javax.swing.JRadioButton();
        info_Cachly_KVCL = new javax.swing.JRadioButton();

        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel31.setText("Đã thực hiện test Covid-19 chưa ?");

        jLabel32.setText("Thời gian bắt đầu cách ly");

        jLabel34.setText("Kết quả test Covid-19 lần gần nhất");

        jLabel35.setText("ID nhân khẩu");

        jLabel36.setText("Số CCCD");

        jLabel38.setText("Họ và tên");

        info_timeTest_PC_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_timeTest_PC_textActionPerformed(evt);
            }
        });

        update_PC_Btn.setText("Cập nhật");
        update_PC_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_PC_BtnActionPerformed(evt);
            }
        });

        jLabel39.setText("Hình thức kiểm tra");

        info_done_test.setText("Đã thực hiện");
        info_done_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_done_testActionPerformed(evt);
            }
        });

        info_notdone_test.setText("Chưa thực hiện");
        info_notdone_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_notdone_testActionPerformed(evt);
            }
        });

        info_CCCD_PC_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_CCCD_PC_textActionPerformed(evt);
            }
        });

        jLabel40.setText("Thời gian kiểm tra");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel44.setText("Nếu dương tính điền thông tin bên dưới");

        info_positive.setText("Dương tính");

        info_negative.setText("Âm tính");
        info_negative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_negativeActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Nếu đã thực hiện điền thông tin bên dưới ");

        jLabel23.setText("Mức độ cách ly");

        jLabel22.setText("Trạng thái cách ly");

        info_level_F2.setText("1 (F2)");
        info_level_F2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_level_F2ActionPerformed(evt);
            }
        });

        info_level_F1.setText("2 (F1)");

        info_level_F0.setText("3 (F0)");

        info_Cachly_TN.setText("Tại nhà");

        info_Cachly_KVCL.setText("Tại khu vực cách ly ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(info_Cachly_KVCL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(info_startTimeCL_PC_text)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(info_IDNK_PC_text)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(info_done_test, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(info_notdone_test, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(info_name_PC_text)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(info_positive, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(info_negative, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(info_methodTest_PC_text, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(info_Cachly_TN, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(info_CCCD_PC_text)
                                        .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(info_timeTest_PC_text)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(info_level_F2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(info_level_F1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(info_level_F0, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(update_PC_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(142, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info_IDNK_PC_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel36))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(info_name_PC_text, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(info_CCCD_PC_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info_done_test)
                    .addComponent(info_notdone_test))
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(info_positive)
                            .addComponent(info_negative))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel39))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(info_timeTest_PC_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info_methodTest_PC_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel44)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info_startTimeCL_PC_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info_level_F2)
                    .addComponent(info_level_F1)
                    .addComponent(info_level_F0))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info_Cachly_TN)
                    .addComponent(update_PC_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info_Cachly_KVCL)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {info_IDNK_PC_text, info_methodTest_PC_text, info_name_PC_text, info_startTimeCL_PC_text, info_timeTest_PC_text});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1048, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void info_timeTest_PC_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_timeTest_PC_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_timeTest_PC_textActionPerformed

    private void update_PC_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_PC_BtnActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(info_IDNK_PC_text, sb, "Vui lòng nhập ID nhân khẩu!");
        DataValidator.validateEmpty(info_name_PC_text, sb, "Vui lòng nhập họ và tên!");
        DataValidator.validateEmpty(info_CCCD_PC_text, sb, "Vui lòng nhập CCCD!");
        DataValidator.validateEmpty(info_startTimeCL_PC_text, sb, "Vui lòng nhập thời gian bắt đầu cách ly!");
        DataValidator.validateEmpty(info_timeTest_PC_text, sb, "Vui lòng nhập thời gian kiểm tra Covid-19!");
        DataValidator.validateEmpty(info_methodTest_PC_text, sb, "Vui lòng nhập hình thức test Covid-19!");

        if (!info_done_test.isSelected() && !info_notdone_test.isSelected()){
            sb.append("Vui lòng cho biết đã test Covid-19 chưa!\n");
        }

        if (!info_Cachly_TN.isSelected() && !info_Cachly_KVCL.isSelected()){
            sb.append("Vui lòng cho biết trạng thái cách ly Covid-19!\n");
        }

        if (!info_positive.isSelected() && !info_negative.isSelected()){
            sb.append("Vui lòng cho biết kết quả test Covid-19!\n");
        }

        if (!info_level_F2.isSelected() && !info_level_F1.isSelected() && !info_level_F0.isSelected()){
            sb.append("Vui lòng cho biết mức độ cách ly Covid-19 của bạn!\n");
        }

        if (sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return;

        }
        CachLyDao dao = new CachLyDao();
        try{

            if (dao.IsExist(info_CCCD_PC_text.getText(), info_IDNK_PC_text.getText())){
                MessageDialogHelper.showErrorDialog(this, "Thông tin nhân khẩu đã tồn tại, hãy cập nhật", "Lỗi");
            }else{
                MessageDialogHelper.showMessageDialog(this, "Thêm thông tin thành công!", "Thành công");
                String test = info_done_test.isSelected() ? "Đã thực hiện" : "Chưa thực hiện";
                String result = info_positive.isSelected() ? "Dương tính" : "Âm tính";
                String status = info_Cachly_TN.isSelected() ? "Tại nhà" : "Tại khu vực cách ly";
                String level;
                if(info_level_F2.isSelected()) level = "1(F2)";
                else if(info_level_F1.isSelected()) level = "1(F1)";
                else level = "3(F0)";
                CachLy cl = new CachLy(info_IDNK_PC_text.getText(), info_CCCD_PC_text.getText(),
                    info_name_PC_text.getText(), test, result,info_timeTest_PC_text.getText(),
                    info_methodTest_PC_text.getText(), info_startTimeCL_PC_text.getText(), level, status);

                dao.InsertCL(cl);
            }
        }catch (Exception e){
            printStackTrace();
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_update_PC_BtnActionPerformed

    private void info_done_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_done_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_done_testActionPerformed

    private void info_notdone_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_notdone_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_notdone_testActionPerformed

    private void info_CCCD_PC_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_CCCD_PC_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_CCCD_PC_textActionPerformed

    private void info_negativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_negativeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_negativeActionPerformed

    private void info_level_F2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_level_F2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_level_F2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField info_CCCD_PC_text;
    private javax.swing.JRadioButton info_Cachly_KVCL;
    private javax.swing.JRadioButton info_Cachly_TN;
    private javax.swing.JTextField info_IDNK_PC_text;
    private javax.swing.JRadioButton info_done_test;
    private javax.swing.JRadioButton info_level_F0;
    private javax.swing.JRadioButton info_level_F1;
    private javax.swing.JRadioButton info_level_F2;
    private javax.swing.JTextField info_methodTest_PC_text;
    private javax.swing.JTextField info_name_PC_text;
    private javax.swing.JRadioButton info_negative;
    private javax.swing.JRadioButton info_notdone_test;
    private javax.swing.JRadioButton info_positive;
    private javax.swing.JTextField info_startTimeCL_PC_text;
    private javax.swing.JTextField info_timeTest_PC_text;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton update_PC_Btn;
    // End of variables declaration//GEN-END:variables

}
