/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlynhankhau.ui;

import com.mycompany.quanlynhankhau.Helpers.DataValidator;
import com.mycompany.quanlynhankhau.Helpers.MessageDialogHelper;
import com.mycompany.quanlynhankhau.Thongtin.HoKhau;
import com.mycompany.quanlynhankhau.Thongtin.NhanKhau;
import com.mycompany.quanlynhankhau.dao.HoKhauDao;
import com.mycompany.quanlynhankhau.dao.NhanKhauDao;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author HP
 */
public class HK_Info extends javax.swing.JPanel {
    private String currentHK_ID;
    private String currentHK_CCCD;
    /**
     * Creates new form HK_Info
     */
    public HK_Info() {
        initComponents();
    }

    public HK_Info(HoKhau hk) {
        initComponents();
        
        info_CCCD_HK_text.setText(hk.getCccd());
        info_ID_HK_text.setText(hk.getIdHK());
        info_HTCH_HK_text.setText(hk.getHoTen());
        info_note_HK_text.setText(hk.getGhiChu());  
        currentHK_ID = info_ID_HK_text.getText();
        
        ShowAllHKMembers(hk);
    }
    
    public void SetEditableTextField(boolean isEditable){
        info_CCCD_HK_text.setEditable(isEditable);
        info_ID_HK_text.setEditable(false); 
        info_HTCH_HK_text.setEditable(isEditable);
        info_note_HK_text.setEditable(isEditable);
        update_HK_Btn.setVisible(isEditable);
    }
    
    private void ShowAllHKMembers(HoKhau hk){
        JTableHeader tableHeader = show_HK_members_tables.getTableHeader();
        Font headerFont = new Font("Verdana", Font.PLAIN, 20);
        tableHeader.setFont(headerFont);
        
        HoKhauDao dao = new HoKhauDao();
        try{
            List<NhanKhau> hkList = dao.GetNKInHK(hk.getIdHK());
            DefaultTableModel model = (DefaultTableModel)show_HK_members_tables.getModel();
            
            Object[] row = new Object[5];
            for (int i = 0; i < hkList.size(); i++){
                row[0] = hkList.get(i).getIdHK();
                row[1] = hkList.get(i).getIdNK();
                row[2] = hkList.get(i).getHoTen();
                row[3] = hkList.get(i).getCccd();
                row[4] = hkList.get(i).getQuanHeVoiChuHo();

                model.addRow(row);
            }
        }catch(Exception e){
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        info_CCCD_HK_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        info_ID_HK_text = new javax.swing.JTextField();
        info_HTCH_HK_text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        update_HK_Btn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        info_note_HK_text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_HK_members_tables = new javax.swing.JTable();

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        info_CCCD_HK_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Số CCCD");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("ID hộ khẩu");

        info_ID_HK_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        info_HTCH_HK_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("Họ và tên chủ hộ");

        update_HK_Btn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        update_HK_Btn.setText("Cập nhật");
        update_HK_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_HK_BtnActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setText("Ghi chú");

        info_note_HK_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        show_HK_members_tables.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        show_HK_members_tables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Hộ khẩu", "ID Nhân khẩu", "Họ tên", "CCCD", "Quan hệ với chủ hộ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        show_HK_members_tables.setRowHeight(50);
        jScrollPane1.setViewportView(show_HK_members_tables);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 203, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(update_HK_Btn)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(info_HTCH_HK_text)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(info_ID_HK_text))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(148, 148, 148)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(info_CCCD_HK_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(info_note_HK_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 203, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {info_CCCD_HK_text, info_HTCH_HK_text, info_ID_HK_text, info_note_HK_text});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info_ID_HK_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info_CCCD_HK_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(3, 3, 3)
                        .addComponent(info_HTCH_HK_text, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(info_note_HK_text, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update_HK_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {info_CCCD_HK_text, info_HTCH_HK_text, info_ID_HK_text, info_note_HK_text});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void update_HK_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_HK_BtnActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(info_CCCD_HK_text, sb, "Vui lòng nhập số CCCD!");
        DataValidator.validateEmpty(info_HTCH_HK_text, sb, "Vui lòng nhập họ và tên chủ hộ!");

        if (sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return;
        }
        NhanKhauDao nkdao = new NhanKhauDao();
        HoKhauDao hkdao = new HoKhauDao();
        try{
            NhanKhau nk = nkdao.GetNK(info_CCCD_HK_text.getText(), "");
            if (nk == null){
                MessageDialogHelper.showErrorDialog(this, "Không tồn tại nhân khẩu!", "Lỗi");
            }else if(!nk.getHoTen().equals(info_HTCH_HK_text.getText())){
                MessageDialogHelper.showErrorDialog(this, "Họ tên và số CCCD không tương ứng!", "Lỗi");
            }else if (!nk.getIdHK().equals(currentHK_ID)){
                MessageDialogHelper.showErrorDialog(this, "Nhân khẩu không thuộc hộ khẩu!", "Lỗi");
            }else{
                MessageDialogHelper.showMessageDialog(this, "Cập nhật thông tin hộ khẩu thành công!", "Thành công");
                HoKhau hk = new HoKhau(info_ID_HK_text.getText(),
                info_HTCH_HK_text.getText(), info_CCCD_HK_text.getText(), info_note_HK_text.getText());

                hkdao.UpdateHK(hk);
            }
            

        }catch (Exception e){
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_update_HK_BtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField info_CCCD_HK_text;
    private javax.swing.JTextField info_HTCH_HK_text;
    private javax.swing.JTextField info_ID_HK_text;
    private javax.swing.JTextField info_note_HK_text;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable show_HK_members_tables;
    private javax.swing.JButton update_HK_Btn;
    // End of variables declaration//GEN-END:variables
}
