/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlynhankhau.ui;

import com.mycompany.quanlynhankhau.Helpers.DataValidator;
import com.mycompany.quanlynhankhau.Helpers.MessageDialogHelper;
import com.mycompany.quanlynhankhau.Thongtin.NhanKhau;
import com.mycompany.quanlynhankhau.dao.NhanKhauDao;

/**
 *
 * @author minhd
 */
public class NK_Info extends javax.swing.JPanel {
    private String currentNK_ID;
    private String currentNK_CCCD;
    /**
     * Creates new form NK_Info
     */
    public NK_Info() {
        initComponents();
    }
    
    public NK_Info(NhanKhau nk){
        initComponents();
        
        info_CCCD_NK_text.setText(nk.getCccd());
        DataValidator.SetDateFromString(nk.getNgaySinh(), DoB_day, DoB_month, DoB_year);
        info_Ethnic_NK_text.setText(nk.getDanToc());
        info_Hometown_NK_text.setText(nk.getQueQuan());
        info_ID_HK_text.setText(nk.getIdHK());
        info_ID_NK_text.setText(nk.getIdNK());
        info_Job_NK_text.setText(nk.getNgheNghiep());
        info_Name_NK_text.setText(nk.getHoTen());
        info_Relation_NK_text.setText(nk.getQuanHeVoiChuHo());
        info_diachiTT_text.setText(nk.getDiachithuongtru());
        info_note_text.setText(nk.getGhiChu());
        
        if (nk.getGioiTinh().equals("Nam")){
            info_isMale.setSelected(true);
        }
        else{
            info_isFemale.setSelected(true);
        }
        
        currentNK_ID = info_ID_HK_text.getText();
    }
    
    public void SetEditableTextField(boolean isEditable){
        info_CCCD_NK_text.setEditable(isEditable);
        DoB_day.setEnabled(isEditable);
        DoB_month.setEnabled(isEditable);
        DoB_year.setEnabled(isEditable);             
        info_Ethnic_NK_text.setEditable(isEditable);
        info_Hometown_NK_text.setEditable(isEditable);
        info_ID_HK_text.setEditable(isEditable);
        info_ID_NK_text.setEditable(isEditable);
        info_Job_NK_text.setEditable(isEditable);
        info_Name_NK_text.setEditable(isEditable);
        info_Relation_NK_text.setEditable(isEditable);
        info_diachiTT_text.setEditable(isEditable);
        info_note_text.setEditable(isEditable);
        info_isMale.setEnabled(isEditable);        
        info_isFemale.setEnabled(isEditable);

        update_NK_Btn.setVisible(isEditable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        info_CCCD_NK_text = new javax.swing.JTextField();
        info_Hometown_NK_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        info_ID_NK_text = new javax.swing.JTextField();
        info_Name_NK_text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        info_Ethnic_NK_text = new javax.swing.JTextField();
        update_NK_Btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        info_ID_HK_text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        info_Job_NK_text = new javax.swing.JTextField();
        info_Relation_NK_text = new javax.swing.JTextField();
        info_diachiTT_text = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        info_note_text = new javax.swing.JTextField();
        info_isMale = new javax.swing.JRadioButton();
        info_isFemale = new javax.swing.JRadioButton();
        DoB_year = new javax.swing.JComboBox<>();
        jLabel62 = new javax.swing.JLabel();
        DoB_month = new javax.swing.JComboBox<>();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        DoB_day = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1308, 600));

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 553));

        info_CCCD_NK_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        info_Hometown_NK_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Số CCCD");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setText("Quê quán");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("ID nhân khẩu");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("ID hộ khẩu");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setText("Quan hệ với chủ hộ");

        info_ID_NK_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        info_Name_NK_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("Họ và tên");

        info_Ethnic_NK_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        info_Ethnic_NK_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_Ethnic_NK_textActionPerformed(evt);
            }
        });

        update_NK_Btn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        update_NK_Btn.setText("Cập nhật");
        update_NK_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_NK_BtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setText("Giới tính");

        info_ID_HK_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        info_ID_HK_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_ID_HK_textActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Dân tộc");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setText("Nghề nghiệp");

        info_Job_NK_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        info_Job_NK_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_Job_NK_textActionPerformed(evt);
            }
        });

        info_Relation_NK_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        info_Relation_NK_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_Relation_NK_textActionPerformed(evt);
            }
        });

        info_diachiTT_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        info_diachiTT_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_diachiTT_textActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel14.setText("Địa chỉ thường trú");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setText("Ghi chú");

        info_note_text.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        buttonGroup1.add(info_isMale);
        info_isMale.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        info_isMale.setText("Nam");

        buttonGroup1.add(info_isFemale);
        info_isFemale.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        info_isFemale.setText("Nữ");

        DoB_year.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DoB_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", " " }));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel62.setText("Ngày");

        DoB_month.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DoB_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel63.setText("Tháng");

        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel64.setText("Năm");

        DoB_day.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DoB_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " ", " " }));
        DoB_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoB_dayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Dân tộc");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(info_Name_NK_text, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(info_ID_NK_text, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(info_Hometown_NK_text, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(DoB_day, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DoB_month, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DoB_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(info_isMale)
                        .addGap(18, 18, 18)
                        .addComponent(info_isFemale))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info_Ethnic_NK_text)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(info_ID_HK_text, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(info_CCCD_NK_text, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_NK_Btn)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(info_Relation_NK_text)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(info_diachiTT_text, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(info_note_text, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info_Job_NK_text))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {info_CCCD_NK_text, info_Ethnic_NK_text, info_Hometown_NK_text, info_ID_HK_text, info_ID_NK_text, info_Job_NK_text, info_Name_NK_text, info_Relation_NK_text, info_diachiTT_text, info_note_text});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(info_Job_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(info_Relation_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(12, 12, 12)
                        .addComponent(info_diachiTT_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(info_note_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(info_CCCD_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(info_ID_HK_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(info_Ethnic_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel63)
                                            .addComponent(jLabel64)
                                            .addComponent(jLabel62))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel11))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(DoB_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(DoB_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(DoB_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(info_Hometown_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(info_isMale)
                                                .addComponent(info_isFemale))))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(info_ID_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10)
                                    .addGap(49, 49, 49))
                                .addComponent(info_Name_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(update_NK_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {info_CCCD_NK_text, info_Ethnic_NK_text, info_Hometown_NK_text, info_ID_HK_text, info_ID_NK_text, info_Job_NK_text, info_Name_NK_text, info_Relation_NK_text, info_diachiTT_text, info_note_text});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void info_Ethnic_NK_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_Ethnic_NK_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_Ethnic_NK_textActionPerformed

    private void update_NK_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_NK_BtnActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(info_CCCD_NK_text, sb, "Vui lòng nhập số CCCD!");        
        DataValidator.validateEmpty(info_ID_HK_text, sb, "Vui lòng nhập ID hộ khẩu!");
        DataValidator.DateValidator(DoB_day.getSelectedItem().toString(), DoB_month.getSelectedItem().toString(), DoB_year.getSelectedItem().toString(), sb, "Ngày sinh không hợp lệ!");
        DataValidator.validateEmpty(info_Ethnic_NK_text, sb, "Vui lòng nhập dân tộc!");
        DataValidator.validateEmpty(info_Hometown_NK_text, sb, "Vui lòng nhập quê quán!");
        DataValidator.validateEmpty(info_Job_NK_text, sb, "Vui lòng nhập nghề nghiệp!");
        DataValidator.validateEmpty(info_Name_NK_text, sb, "Vui lòng nhập họ và tên nhân khẩu!");
        DataValidator.validateEmpty(info_Relation_NK_text, sb, "Vui lòng cho biết quan hệ với chủ hộ!");
        DataValidator.validateEmpty(info_diachiTT_text, sb, "Vui lòng nhập địa chỉ thường trú!");
        DataValidator.validateEmpty(info_diachiTT_text, sb, "Vui lòng nhập nơi đăng ký thường trú!");

        if (!info_isMale.isSelected() && !info_isFemale.isSelected()){
            sb.append("Vui lòng chọn giới tính!\n");
        }

        if (sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return;
        
        }
        
        NhanKhauDao dao = new NhanKhauDao();
        try{
            
            if (dao.GetNK(info_CCCD_NK_text.getText(), info_ID_HK_text.getText()) != null){

            }
            MessageDialogHelper.showMessageDialog(this, "Cập nhật thông tin nhân khẩu thành công!", "Thành công");
            String gentle = info_isMale.isSelected() ? "Nam" : "Nữ";
            String dob = DataValidator.DatePerformer(DoB_day.getSelectedItem().toString(), DoB_month.getSelectedItem().toString(), DoB_year.getSelectedItem().toString());
            
            NhanKhau nk = new NhanKhau(info_ID_NK_text.getText(), info_ID_HK_text.getText(), info_CCCD_NK_text.getText(), 
                                            info_Name_NK_text.getText(), dob, gentle, info_Relation_NK_text.getText(), 
                                            info_Hometown_NK_text.getText(), info_Ethnic_NK_text.getText(), info_Job_NK_text.getText(),
                                            info_diachiTT_text.getText(), info_note_text.getText());
                
            dao.UpdateNK(nk);    
            
        }catch (Exception e){
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        } 
    }//GEN-LAST:event_update_NK_BtnActionPerformed

    private void info_ID_HK_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_ID_HK_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_ID_HK_textActionPerformed

    private void info_Job_NK_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_Job_NK_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_Job_NK_textActionPerformed

    private void info_Relation_NK_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_Relation_NK_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_Relation_NK_textActionPerformed

    private void info_diachiTT_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_diachiTT_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_diachiTT_textActionPerformed

    private void DoB_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoB_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoB_dayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DoB_day;
    private javax.swing.JComboBox<String> DoB_month;
    private javax.swing.JComboBox<String> DoB_year;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField info_CCCD_NK_text;
    private javax.swing.JTextField info_Ethnic_NK_text;
    private javax.swing.JTextField info_Hometown_NK_text;
    private javax.swing.JTextField info_ID_HK_text;
    private javax.swing.JTextField info_ID_NK_text;
    private javax.swing.JTextField info_Job_NK_text;
    private javax.swing.JTextField info_Name_NK_text;
    private javax.swing.JTextField info_Relation_NK_text;
    private javax.swing.JTextField info_diachiTT_text;
    private javax.swing.JRadioButton info_isFemale;
    private javax.swing.JRadioButton info_isMale;
    private javax.swing.JTextField info_note_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton update_NK_Btn;
    // End of variables declaration//GEN-END:variables
}
