/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlynhankhau.ui;

import com.mycompany.quanlynhankhau.Helpers.DataValidator;
import com.mycompany.quanlynhankhau.Helpers.MessageDialogHelper;
import com.mycompany.quanlynhankhau.Thongtin.NhanKhau;
import com.mycompany.quanlynhankhau.dao.NhanKhauDao;
import static com.sun.corba.se.impl.util.Utility.printStackTrace;

/**
 *
 * @author minhd
 */
public class NK_Info extends javax.swing.JPanel {
    private String currentNK_ID;
    private String currentNK_CCCD;
    /**
     * Creates new form NK_Info
     */
    public NK_Info() {
        initComponents();
    }
    
    public NK_Info(NhanKhau nk){
        initComponents();
        
        info_CCCD_NK_text.setText(nk.getCccd());
        info_DoB_NK_text.setText(nk.getNgaySinh());
        info_Ethnic_NK_text.setText(nk.getDanToc());
        info_Hometown_NK_text.setText(nk.getQueQuan());
        info_ID_HK_text.setText(nk.getIdHK());
        info_ID_NK_text.setText(nk.getIdNK());
        info_Job_NK_text.setText(nk.getNgheNghiep());
        info_Name_NK_text.setText(nk.getHoTen());
        info_Relation_NK_text.setText(nk.getQuanHeVoiChuHo());
        info_ngayDKTT_text.setText(nk.getNgayDkThuongTru());
        info_noiDKTT_text.setText(nk.getNoiDkThuongTru());
        info_note_text.setText(nk.getGhiChu());
        
        if (nk.getGioiTinh().equals("Nam")){
            info_isMale.setSelected(true);
        }
        else{
            info_isFemale.setSelected(true);
        }
        
        currentNK_ID = info_ID_HK_text.getText();
    }
    
    public void SetEditableTextField(boolean isEditable){
        info_CCCD_NK_text.setEditable(isEditable);
        info_DoB_NK_text.setEditable(isEditable);
        info_Ethnic_NK_text.setEditable(isEditable);
        info_Hometown_NK_text.setEditable(isEditable);
        info_ID_HK_text.setEditable(isEditable);
        info_ID_NK_text.setEditable(isEditable);
        info_Job_NK_text.setEditable(isEditable);
        info_Name_NK_text.setEditable(isEditable);
        info_Relation_NK_text.setEditable(isEditable);
        info_ngayDKTT_text.setEditable(isEditable);
        info_noiDKTT_text.setEditable(isEditable);
        info_note_text.setEditable(isEditable);
        info_isMale.setEnabled(isEditable);        
        info_isFemale.setEnabled(isEditable);

        update_NK_Btn.setVisible(isEditable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        info_CCCD_NK_text = new javax.swing.JTextField();
        info_DoB_NK_text = new javax.swing.JTextField();
        info_Hometown_NK_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        info_ID_NK_text = new javax.swing.JTextField();
        info_Name_NK_text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        info_Ethnic_NK_text = new javax.swing.JTextField();
        update_NK_Btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        info_ID_HK_text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        info_Job_NK_text = new javax.swing.JTextField();
        info_Relation_NK_text = new javax.swing.JTextField();
        info_noiDKTT_text = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        info_ngayDKTT_text = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        info_note_text = new javax.swing.JTextField();
        info_isMale = new javax.swing.JRadioButton();
        info_isFemale = new javax.swing.JRadioButton();

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setText("Ngày sinh");

        jLabel4.setText("Số CCCD");

        jLabel5.setText("Quê quán");

        jLabel6.setText("ID nhân khẩu");

        jLabel7.setText("ID hộ khẩu");

        jLabel8.setText("Quan hệ với chủ hộ");

        jLabel10.setText("Họ và tên");

        info_Ethnic_NK_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_Ethnic_NK_textActionPerformed(evt);
            }
        });

        update_NK_Btn.setText("Cập nhật");
        update_NK_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_NK_BtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Giới tính");

        info_ID_HK_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_ID_HK_textActionPerformed(evt);
            }
        });

        jLabel1.setText("Dân tộc");

        jLabel12.setText("Nghề nghiệp");

        info_Job_NK_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_Job_NK_textActionPerformed(evt);
            }
        });

        info_Relation_NK_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_Relation_NK_textActionPerformed(evt);
            }
        });

        info_noiDKTT_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_noiDKTT_textActionPerformed(evt);
            }
        });

        jLabel13.setText("Ngày đăng kí thường trú ");

        jLabel14.setText("Nơi đăng kí thướng trú");

        jLabel15.setText("Ghi chú");

        buttonGroup1.add(info_isMale);
        info_isMale.setText("Nam");

        buttonGroup1.add(info_isFemale);
        info_isFemale.setText("Nữ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(info_Hometown_NK_text, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(info_DoB_NK_text)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(info_Name_NK_text)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(info_ID_NK_text)
                            .addComponent(info_Ethnic_NK_text, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(info_isMale)
                        .addGap(18, 18, 18)
                        .addComponent(info_isFemale))
                    .addComponent(update_NK_Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(info_ID_HK_text)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(info_Job_NK_text)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(info_Relation_NK_text)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(info_ngayDKTT_text)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(info_CCCD_NK_text, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(info_noiDKTT_text, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(info_note_text, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {info_CCCD_NK_text, info_DoB_NK_text, info_Ethnic_NK_text, info_Hometown_NK_text, info_ID_HK_text, info_ID_NK_text, info_Job_NK_text, info_Name_NK_text, info_Relation_NK_text, info_ngayDKTT_text, info_noiDKTT_text, info_note_text});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(info_ID_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(info_CCCD_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(info_ID_HK_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(info_Name_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info_Job_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info_DoB_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info_Relation_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info_Hometown_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info_ngayDKTT_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info_Ethnic_NK_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info_noiDKTT_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info_isMale)
                    .addComponent(info_isFemale))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info_note_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_NK_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {info_CCCD_NK_text, info_DoB_NK_text, info_Ethnic_NK_text, info_Hometown_NK_text, info_ID_HK_text, info_ID_NK_text, info_Job_NK_text, info_Name_NK_text, info_Relation_NK_text, info_ngayDKTT_text, info_noiDKTT_text, info_note_text});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void info_Ethnic_NK_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_Ethnic_NK_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_Ethnic_NK_textActionPerformed

    private void update_NK_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_NK_BtnActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(info_CCCD_NK_text, sb, "Vui lòng nhập số CCCD!");
        DataValidator.validateEmpty(info_DoB_NK_text, sb, "Vui lòng nhập ngày sinh!");
        DataValidator.validateEmpty(info_Ethnic_NK_text, sb, "Vui lòng nhập dân tộc!");
        DataValidator.validateEmpty(info_Hometown_NK_text, sb, "Vui lòng nhập quê quán!");
        DataValidator.validateEmpty(info_Job_NK_text, sb, "Vui lòng nhập nghề nghiệp!");
        DataValidator.validateEmpty(info_Name_NK_text, sb, "Vui lòng nhập họ và tên nhân khẩu!");
        DataValidator.validateEmpty(info_Relation_NK_text, sb, "Vui lòng cho biết quan hệ với chủ hộ!");
        DataValidator.validateEmpty(info_ngayDKTT_text, sb, "Vui lòng nhập ngày đăng ký thường trú!");
        DataValidator.validateEmpty(info_noiDKTT_text, sb, "Vui lòng nhập nơi đăng ký thường trú!");

        if (!info_isMale.isSelected() && !info_isFemale.isSelected()){
            sb.append("Vui lòng chọn giới tính!\n");
        }

        if (sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return;
        
        }
        
    
        NhanKhauDao dao = new NhanKhauDao();
        try{
            
            if (dao.IsExist(info_CCCD_NK_text.getText(), info_ID_HK_text.getText()) != null){

            }
            MessageDialogHelper.showMessageDialog(this, "Cập nhật thông tin nhân khẩu thành công!", "Thành công");
            String gentle = info_isMale.isSelected() ? "Nam" : "Nữ";
            NhanKhau nk = new NhanKhau(info_ID_NK_text.getText(), info_ID_HK_text.getText(), info_CCCD_NK_text.getText(), 
                                            info_Name_NK_text.getText(), info_DoB_NK_text.getText(), gentle, info_Relation_NK_text.getText(), 
                                            info_Hometown_NK_text.getText(), info_Ethnic_NK_text.getText(), info_Job_NK_text.getText(),
                                            info_ngayDKTT_text.getText(), info_noiDKTT_text.getText(), info_note_text.getText());
                
            dao.UpdateNK(nk);    
            
        }catch (Exception e){
            printStackTrace();
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        } 
    }//GEN-LAST:event_update_NK_BtnActionPerformed

    private void info_ID_HK_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_ID_HK_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_ID_HK_textActionPerformed

    private void info_Job_NK_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_Job_NK_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_Job_NK_textActionPerformed

    private void info_Relation_NK_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_Relation_NK_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_Relation_NK_textActionPerformed

    private void info_noiDKTT_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_noiDKTT_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_noiDKTT_textActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField info_CCCD_NK_text;
    private javax.swing.JTextField info_DoB_NK_text;
    private javax.swing.JTextField info_Ethnic_NK_text;
    private javax.swing.JTextField info_Hometown_NK_text;
    private javax.swing.JTextField info_ID_HK_text;
    private javax.swing.JTextField info_ID_NK_text;
    private javax.swing.JTextField info_Job_NK_text;
    private javax.swing.JTextField info_Name_NK_text;
    private javax.swing.JTextField info_Relation_NK_text;
    private javax.swing.JRadioButton info_isFemale;
    private javax.swing.JRadioButton info_isMale;
    private javax.swing.JTextField info_ngayDKTT_text;
    private javax.swing.JTextField info_noiDKTT_text;
    private javax.swing.JTextField info_note_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton update_NK_Btn;
    // End of variables declaration//GEN-END:variables
}
