/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlynhankhau.ui;

import com.mycompany.quanlynhankhau.Helpers.DataValidator;
import com.mycompany.quanlynhankhau.Helpers.MessageDialogHelper;
import com.mycompany.quanlynhankhau.Thongtin.CachLy;
import com.mycompany.quanlynhankhau.Thongtin.HoKhau;
import com.mycompany.quanlynhankhau.Thongtin.NhanKhau;
import com.mycompany.quanlynhankhau.dao.CachLyDao;
import com.mycompany.quanlynhankhau.dao.HoKhauDao;
import com.mycompany.quanlynhankhau.dao.NhanKhauDao;

/**
 *
 * @author HP
 */
public class UserPageForm extends javax.swing.JFrame {

    /**
     * Creates new form HomepageForm
     */
    public UserPageForm() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        HK_Tab = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        search_ID_NK = new javax.swing.JTextField();
        Show_NK_Btn = new javax.swing.JButton();
        ShowNKInfo = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        Search_ID_HK = new javax.swing.JTextField();
        Show_HK_Btn = new javax.swing.JButton();
        ShowHKInfo = new javax.swing.JTabbedPane();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        Search_IDNK_PC = new javax.swing.JTextField();
        Show_PC_Btn = new javax.swing.JButton();
        ShowPCInfo = new javax.swing.JTabbedPane();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        logoutBtn = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Trang thông tin quản lý nhân khẩu tổ dân cư số 7");

        HK_Tab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        HK_Tab.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N

        jTabbedPane5.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Nhập ID hoặc CCCD nhân khẩu:");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        search_ID_NK.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        search_ID_NK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_ID_NKActionPerformed(evt);
            }
        });

        Show_NK_Btn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Show_NK_Btn.setText("Hiển thị");
        Show_NK_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_NK_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(530, Short.MAX_VALUE)
                        .addComponent(search_ID_NK, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 529, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShowNKInfo))))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Show_NK_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_ID_NK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Show_NK_Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowNKInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Hiển thị", jPanel4);

        HK_Tab.addTab("Nhân khẩu", jTabbedPane5);

        jTabbedPane6.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Nhập ID hộ khẩu hoặc CCCD chủ hộ");

        Search_ID_HK.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Search_ID_HK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ID_HKActionPerformed(evt);
            }
        });

        Show_HK_Btn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Show_HK_Btn.setText("Hiển thị");
        Show_HK_Btn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Show_HK_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_HK_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, 1303, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Search_ID_HK, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(ShowHKInfo)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Show_HK_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search_ID_HK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Show_HK_Btn)
                .addGap(24, 24, 24)
                .addComponent(ShowHKInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Hiển thị", jPanel9);

        HK_Tab.addTab("Hộ khẩu", jTabbedPane6);

        jTabbedPane7.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Nhập ID hoặc CCCD nhân khẩu ");

        Search_IDNK_PC.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        Show_PC_Btn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Show_PC_Btn.setText("Hiển thị");
        Show_PC_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_PC_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShowPCInfo)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap(533, Short.MAX_VALUE)
                        .addComponent(Search_IDNK_PC, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 526, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Show_PC_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search_IDNK_PC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Show_PC_Btn)
                .addGap(18, 18, 18)
                .addComponent(ShowPCInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane7.addTab("Hiển thị", jPanel8);

        HK_Tab.addTab("Phòng Covid", jTabbedPane7);
        HK_Tab.addTab("Thông báo", jTabbedPane8);

        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        logoutBtn.setText("Đăng xuất");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1323, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HK_Tab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoutBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HK_Tab, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Show_HK_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_HK_BtnActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(Search_ID_HK, sb, "Vui lòng nhập ID hộ khẩu hoặc số CCCD chủ hộ cần hiển thị!");
        
        if (sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return;
        }
        
        HoKhauDao dao = new HoKhauDao();
        try{
            HoKhau hk = dao.SearchHK(Search_ID_HK.getText());
            if (hk == null){
                MessageDialogHelper.showErrorDialog(this, "Hộ khẩu không tồn tại!", "Lỗi");
            }else{
                HK_Info infoTab = new HK_Info(hk);
                infoTab.SetEditableTextField(false);
                ShowHKInfo.removeAll();
                ShowHKInfo.addTab("Hiển thị", infoTab);
            }
        }catch (Exception e){
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        }      
    }//GEN-LAST:event_Show_HK_BtnActionPerformed

    private void Search_ID_HKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ID_HKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_ID_HKActionPerformed

    private void Show_NK_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_NK_BtnActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(search_ID_NK, sb, "Vui lòng nhập ID hoặc CCCD nhân khẩu!");
        if (sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
        }else{
            NhanKhauDao dao = new NhanKhauDao();
            try{
                NhanKhau nk = dao.GetNK(search_ID_NK.getText(), search_ID_NK.getText());
                if (nk == null){
                    MessageDialogHelper.showErrorDialog(this, "Nhân khẩu không tồn tại!", "Lỗi");
                }else{
                    NK_Info infoTab = new NK_Info(nk);
                    infoTab.SetEditableTextField(false);
                    ShowNKInfo.removeAll();
                    ShowNKInfo.addTab("Hiển thị", infoTab);
                }
            }catch (Exception e){
                MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
            }
        }
    }//GEN-LAST:event_Show_NK_BtnActionPerformed

    private void Show_PC_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_PC_BtnActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(Search_IDNK_PC, sb, "Vui lòng nhập ID hoặc CCCD của nhân khẩu cần hiển thị thông tin liên quan Covid-19!");

        if (sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return;
        }

        CachLyDao dao = new CachLyDao();
        try{
            CachLy cl = dao.SearchCL(Search_IDNK_PC.getText());
            if (cl == null){
                MessageDialogHelper.showErrorDialog(this, "Nhân khẩu không có thông tin cách ly!", "Lỗi");
            }else{
                CL_Info infoTab = new CL_Info(cl);
                infoTab.SetEditableTextField(false);
                ShowPCInfo.removeAll();
                ShowPCInfo.addTab("Hiển thị", infoTab);
            }
        }catch (Exception e){
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_Show_PC_BtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void search_ID_NKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_ID_NKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_ID_NKActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane HK_Tab;
    private javax.swing.JTextField Search_IDNK_PC;
    private javax.swing.JTextField Search_ID_HK;
    private javax.swing.JTabbedPane ShowHKInfo;
    private javax.swing.JTabbedPane ShowNKInfo;
    private javax.swing.JTabbedPane ShowPCInfo;
    private javax.swing.JButton Show_HK_Btn;
    private javax.swing.JButton Show_NK_Btn;
    private javax.swing.JButton Show_PC_Btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField search_ID_NK;
    // End of variables declaration//GEN-END:variables



}
